"use client";
import { FormEvent, useState } from "react";
import type { BankAccountRecord } from "@/lib/business/types";

export default function BankAccountManager({ initialAccounts }: { initialAccounts: BankAccountRecord[] }) {
  const [accounts,setAccounts]=useState(initialAccounts),[editing,setEditing]=useState<BankAccountRecord|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  const field="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 outline-none focus:border-blue-600 focus:ring-2 focus:ring-blue-100";
  async function refresh(){const response=await fetch("/api/business/bank-accounts");const data=await response.json();if(response.ok)setAccounts(data.accounts||[]);}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");setMessage("");const form=new FormData(event.currentTarget),payload:Record<string,unknown>=Object.fromEntries(form);payload.active=form.get("active")==="on";try{const response=await fetch(editing?`/api/business/bank-accounts/${editing.id}`:"/api/business/bank-accounts",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage(editing?"Bank account updated.":"Bank account added.");setEditing(null);event.currentTarget.reset();await refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save bank account.");}finally{setBusy(false);}}
  return <div className="grid gap-7 lg:grid-cols-[1fr_1.1fr]"><form key={editing?.id||"new"} onSubmit={submit} className="rounded-3xl bg-white p-7 shadow-sm"><h2 className="text-xl font-bold">{editing?"Edit bank account":"Add bank account"}</h2><p className="mt-2 text-sm text-slate-600">Accounts remain private and only appear on a PDF when selected for that document.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field name="label" label="Account label" value={editing?.label} field={field}/><Field name="bankName" label="Bank name" value={editing?.bankName} field={field}/><Field name="accountName" label="Account holder" value={editing?.accountName} field={field}/><Field name="accountNumber" label="Account number" value={editing?.accountNumber} field={field}/><Field name="branchCode" label="Branch code" value={editing?.branchCode} field={field}/><Field name="accountType" label="Account type" value={editing?.accountType} field={field}/><Field name="swiftBic" label="SWIFT / BIC" value={editing?.swiftBic} field={field}/><label className="text-sm font-bold sm:col-span-2">Payment reference instructions<textarea name="paymentReferenceInstructions" defaultValue={editing?.paymentReferenceInstructions||""} rows={3} className={field}/></label><label className="flex items-center gap-3 text-sm font-bold"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/> Active</label></div>{(message||error)&&<p role="status" className={`mt-5 rounded-xl p-3 text-sm ${error?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-800"}`}>{error||message}</p>}<div className="mt-6 flex gap-3"><button disabled={busy} className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white disabled:opacity-50">{busy?"Saving…":"Save account"}</button>{editing&&<button type="button" onClick={()=>setEditing(null)} className="rounded-xl border px-5 py-3 font-bold">Cancel</button>}</div></form><section><h2 className="text-xl font-bold">Saved accounts</h2><div className="mt-4 space-y-4">{accounts.map(account=><article key={account.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h3 className="font-bold">{account.label}</h3><p className="mt-1 text-sm text-slate-600">{account.bankName} · {account.accountName}</p><p className="mt-1 text-sm text-slate-500">•••• {account.accountNumber.slice(-4)}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${account.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{account.active?"Active":"Inactive"}</span></div><button type="button" onClick={()=>setEditing(account)} className="mt-4 text-sm font-bold text-blue-700">Edit account</button></article>)}{!accounts.length&&<p className="rounded-2xl bg-white p-6 text-slate-600">No bank accounts added yet.</p>}</div></section></div>;
}
function Field({name,label,value,field}:{name:string;label:string;value?:string|null;field:string}){return <label className="text-sm font-bold">{label}<input name={name} defaultValue={value||""} required={["label","bankName","accountName","accountNumber"].includes(name)} className={field}/></label>;}
