"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

async function request(url:string,body?:unknown){const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed.");return data;}

export function DocumentActions({kind,id,status,hasPdf}:{kind:"quote"|"invoice";id:string;status:string;hasPdf:boolean}){
  const router=useRouter(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[canArchive,setCanArchive]=useState(false);
  useEffect(()=>{void fetch("/api/business/settings").then(response=>setCanArchive(response.ok)).catch(()=>setCanArchive(false));},[]);
  async function act(path:string,body?:unknown){setBusy(true);setError("");setMessage("");try{const result=await request(`/api/business/${kind==="quote"?"quotes":"invoices"}/${id}/${path}`,body);if(path==="send")setMessage(`Quote sent to ${result.recipient}.`);if(path==="archive"){router.push(`/secure/${kind==="quote"?"quotes":"invoices"}`);return;}router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Request failed.");}finally{setBusy(false);}}
  return <div className="flex flex-wrap items-center gap-3">
    {status==="DRAFT"&&<button disabled={busy} onClick={()=>act("finalize")} className="rounded-xl bg-blue-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?"Working…":"Finalize & archive PDF"}</button>}
    {kind==="quote"&&status==="SENT"&&<><button disabled={busy} onClick={()=>act("send")} className="rounded-xl bg-cyan-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-50">Send to customer</button><button disabled={busy} onClick={()=>act("status",{status:"ACCEPTED"})} className="rounded-xl bg-emerald-700 px-4 py-3 text-sm font-bold text-white">Mark accepted</button><button disabled={busy} onClick={()=>act("status",{status:"DECLINED"})} className="rounded-xl border border-red-200 px-4 py-3 text-sm font-bold text-red-700">Mark declined</button></>}
    {kind==="invoice"&&!['PAID','CANCELLED','DRAFT'].includes(status)&&<button disabled={busy} onClick={()=>act("cancel")} className="rounded-xl border border-red-200 px-4 py-3 text-sm font-bold text-red-700">Cancel invoice</button>}
    {hasPdf&&<a href={`/api/business/${kind==="quote"?"quotes":"invoices"}/${id}/pdf`} className="rounded-xl border border-blue-200 px-5 py-3 text-sm font-bold text-blue-700">Download PDF</a>}
    {canArchive&&<button disabled={busy} onClick={()=>window.confirm(`Remove this ${kind} from active records? The audit record will be retained.`)&&act("archive")} className="rounded-xl border border-red-200 px-4 py-3 text-sm font-bold text-red-700">Remove {kind}</button>}
    {(error||message)&&<p role="status" className={`w-full text-sm ${error?"text-red-700":"text-emerald-700"}`}>{error||message}</p>}
  </div>;
}

export function ConvertQuoteForm({id}:{id:string}){const router=useRouter(),[error,setError]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));try{const data=await request(`/api/business/quotes/${id}/convert`,values);router.push(`/secure/invoices/${data.id}`);router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Unable to convert quote.");}}return <form onSubmit={submit} className="grid gap-4 rounded-3xl border border-emerald-200 bg-emerald-50 p-6 sm:grid-cols-2"><h2 className="font-bold text-emerald-950 sm:col-span-2">Convert accepted quote to invoice</h2><label className="text-sm font-bold">Invoice date<input name="invoiceDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required className="mt-2 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm font-bold">Due date<input name="dueDate" type="date" required className="mt-2 w-full rounded-xl border px-3 py-2"/></label>{error&&<p className="text-sm text-red-700 sm:col-span-2">{error}</p>}<button className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white sm:col-span-2 sm:w-fit">Convert to invoice</button></form>}

export function PaymentForm({invoiceId,balanceCents}:{invoiceId:string;balanceCents:number}){const router=useRouter(),[error,setError]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;try{await request(`/api/business/invoices/${invoiceId}/payments`,Object.fromEntries(new FormData(form)));form.reset();router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Unable to record payment.");}}const field="mt-2 w-full rounded-xl border border-slate-300 px-3 py-2";return <form onSubmit={submit} className="grid gap-4 rounded-3xl bg-white p-6 shadow-sm sm:grid-cols-2"><h2 className="text-xl font-bold sm:col-span-2">Record payment</h2><label className="text-sm font-bold">Payment date<input name="paymentDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required className={field}/></label><label className="text-sm font-bold">Amount<input name="amount" inputMode="decimal" placeholder={(balanceCents/100).toFixed(2)} required className={field}/></label><label className="text-sm font-bold">Payment method<input name="paymentMethod" placeholder="EFT, card, cash…" required className={field}/></label><label className="text-sm font-bold">Reference<input name="reference" className={field}/></label><label className="text-sm font-bold sm:col-span-2">Notes<textarea name="notes" className={field}/></label>{error&&<p className="text-sm text-red-700 sm:col-span-2">{error}</p>}<button className="rounded-xl bg-blue-700 px-5 py-3 font-bold text-white sm:col-span-2 sm:w-fit">Record payment</button></form>}
