"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { FileUp } from "lucide-react";

export default function UploadForm() {
  const [file,setFile]=useState<File|null>(null);const [uploading,setUploading]=useState(false);const [message,setMessage]=useState("");
  async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!file)return setMessage("Please select a file.");setUploading(true);setMessage("");try{const formData=new FormData();const folderId=new URLSearchParams(window.location.search).get("folder");formData.append("file",file);if(folderId)formData.append("folderId",folderId);const response=await fetch("/api/documents/upload",{method:"POST",body:formData});const result=await response.json();if(!response.ok)throw new Error(result.error||"Upload failed.");window.location.assign(folderId?`/secure/documents?folder=${encodeURIComponent(folderId)}`:"/secure/documents");}catch(error){setMessage(error instanceof Error?error.message:"Unable to upload file.");setUploading(false);}}
  return <div className="mt-6 rounded-3xl bg-white p-6 shadow-sm sm:p-10"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-100 text-blue-700"><FileUp size={27}/></div><h1 className="mt-6 text-3xl font-bold text-slate-900">Upload file</h1><p className="mt-2 text-slate-600">Choose any file to add it to the current folder.</p><form onSubmit={handleSubmit} className="mt-8"><label htmlFor="archive-file" className="flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-3xl border-2 border-dashed border-slate-300 bg-slate-50 p-8 text-center transition hover:border-blue-400 hover:bg-blue-50"><FileUp size={38} className="text-blue-600"/><span className="mt-4 font-semibold text-slate-900">{file?file.name:"Select a file"}</span><span className="mt-2 text-sm text-slate-500">Any format, up to 25 MB by default</span><input id="archive-file" type="file" required className="sr-only" onChange={(event)=>setFile(event.target.files?.[0]??null)}/></label>{message&&<p role="alert" className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{message}</p>}<div className="mt-6 flex justify-end gap-3"><Link href="/secure/documents" className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-semibold text-slate-700">Cancel</Link><button disabled={!file||uploading} className="rounded-xl bg-blue-700 px-6 py-3 text-sm font-semibold text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50">{uploading?"Uploading...":"Upload file"}</button></div></form></div>;
}
