import { randomUUID } from "node:crypto";
import type { PoolClient } from "pg";

import { getPostgresPool, postgresRows, withPostgresTransaction } from "@/lib/db/postgres";
import { parseDocumentInput, text, email, isoDate } from "@/lib/business/validation";
import { parseMoneyToCents, isInvoiceOverdue } from "@/lib/business/finance";
import type { ClientRecord,CompanySettings,FinancialSnapshot,InvoiceRecord,LineRecord,PaymentRecord,QuoteRecord } from "@/lib/business/types";
import { generateFinancialPdf } from "@/lib/business/pdf";
import { deleteR2Object, r2ObjectExists, uploadR2Object } from "@/lib/storage/r2";

const n=(value:unknown)=>Number(value);
const dateOnly=(value:unknown)=>value instanceof Date?value.toISOString().slice(0,10):String(value).slice(0,10);
const iso=(value:unknown)=>value?new Date(value as string|number|Date).toISOString():null;

function mapClient(r:Record<string,unknown>):ClientRecord{return{id:String(r.id),companyName:String(r.company_name),contactPerson:String(r.contact_person),email:String(r.email),phone:String(r.phone),registrationNumber:r.registration_number?String(r.registration_number):null,vatNumber:r.tax_number?String(r.tax_number):null,billingAddress:String(r.billing_address),physicalAddress:r.physical_address?String(r.physical_address):null,notes:r.notes?String(r.notes):null,active:Boolean(r.active),createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!};}
function mapLine(r:Record<string,unknown>):LineRecord{return{id:String(r.id),description:String(r.description),quantityMilli:n(r.quantity_milli),unit:String(r.unit),unitPriceCents:n(r.unit_price_cents),discountCents:n(r.discount_cents),lineTotalCents:n(r.line_total_cents),position:n(r.position)};}
function mapSettings(r:Record<string,unknown>):CompanySettings{return{legalName:String(r.legal_name),tradingName:String(r.trading_name),registrationNumber:r.registration_number?String(r.registration_number):null,vatNumber:r.vat_number?String(r.vat_number):null,address:r.address?String(r.address):null,phone:String(r.phone),email:String(r.email),website:String(r.website),logoPath:String(r.logo_path),quoteValidityDays:n(r.quote_validity_days),invoicePaymentDays:n(r.invoice_payment_days),vatEnabled:Boolean(r.vat_enabled),vatBasisPoints:n(r.vat_basis_points),currency:String(r.currency),quoteTerms:r.quote_terms?String(r.quote_terms):null,invoiceTerms:r.invoice_terms?String(r.invoice_terms):null,paymentInstructions:r.payment_instructions?String(r.payment_instructions):null,bankName:r.bank_name?String(r.bank_name):null,bankAccountName:r.bank_account_name?String(r.bank_account_name):null,bankAccountNumber:r.bank_account_number?String(r.bank_account_number):null,bankBranchCode:r.bank_branch_code?String(r.bank_branch_code):null,bankAccountType:r.bank_account_type?String(r.bank_account_type):null,bankSwiftBic:r.bank_swift_bic?String(r.bank_swift_bic):null,paymentReferenceInstructions:r.payment_reference_instructions?String(r.payment_reference_instructions):null,showBankOnQuotes:Boolean(r.show_bank_on_quotes),showBankOnInvoices:Boolean(r.show_bank_on_invoices),documentFooter:r.document_footer?String(r.document_footer):null};}

export async function getCompanySettings(client?:PoolClient){const runner=client??getPostgresPool();const row=(await runner.query("SELECT * FROM company_settings WHERE id='default'" )).rows[0];if(!row)throw new Error("Company settings are unavailable.");return mapSettings(row);}
export async function updateCompanySettings(body:Record<string,unknown>,userId:string){const vatEnabled=body.vatEnabled===true;const vatPercent=parseMoneyToCents(body.vatPercent||"0");if(vatPercent>10000)throw new Error("VAT cannot exceed 100 percent.");await postgresRows(`UPDATE company_settings SET legal_name=$1,trading_name=$2,registration_number=$3,vat_number=$4,address=$5,phone=$6,email=$7,website=$8,logo_path=$9,quote_validity_days=$10,invoice_payment_days=$11,vat_enabled=$12,vat_basis_points=$13,quote_terms=$14,invoice_terms=$15,payment_instructions=$16,bank_name=$17,bank_account_name=$18,bank_account_number=$19,bank_branch_code=$20,bank_account_type=$21,bank_swift_bic=$22,payment_reference_instructions=$23,show_bank_on_quotes=$24,show_bank_on_invoices=$25,document_footer=$26,updated_at=now(),updated_by=$27 WHERE id='default'`,[text(body.legalName,"Legal name",200),text(body.tradingName,"Trading name",200),text(body.registrationNumber,"Registration number",100,false)||null,text(body.vatNumber,"VAT number",100,false)||null,text(body.address,"Address",1000,false)||null,text(body.phone,"Telephone",50),email(body.email),text(body.website,"Website",300),text(body.logoPath,"Logo path",300),Number(body.quoteValidityDays),Number(body.invoicePaymentDays),vatEnabled,vatEnabled?vatPercent:0,text(body.quoteTerms,"Quote terms",10000,false)||null,text(body.invoiceTerms,"Invoice terms",10000,false)||null,text(body.paymentInstructions,"Payment instructions",5000,false)||null,text(body.bankName,"Bank name",200,false)||null,text(body.bankAccountName,"Account name",200,false)||null,text(body.bankAccountNumber,"Account number",100,false)||null,text(body.bankBranchCode,"Branch code",100,false)||null,text(body.bankAccountType,"Account type",100,false)||null,text(body.bankSwiftBic,"SWIFT/BIC",100,false)||null,text(body.paymentReferenceInstructions,"Payment reference instructions",1000,false)||null,body.showBankOnQuotes===true,body.showBankOnInvoices===true,text(body.documentFooter,"Document footer",2000,false)||null,userId]);return getCompanySettings();}

export async function listClients(search="",includeInactive=false){const rows=await postgresRows(`SELECT * FROM clients WHERE ($1='' OR company_name ILIKE '%'||$1||'%' OR email ILIKE '%'||$1||'%' OR phone ILIKE '%'||$1||'%') AND ($2 OR active) ORDER BY company_name`,[search.slice(0,200),includeInactive]);return rows.map(mapClient);}
export async function getClient(id:string,client?:PoolClient){const runner=client??getPostgresPool();const row=(await runner.query("SELECT * FROM clients WHERE id=$1",[id])).rows[0];return row?mapClient(row):null;}
export async function saveClient(body:Record<string,unknown>,userId:string,id?:string){void userId;const values=[text(body.companyName,"Company name",200),text(body.contactPerson,"Contact person",200),email(body.email),text(body.phone,"Phone",50),text(body.registrationNumber,"Registration number",100,false)||null,text(body.vatNumber,"VAT number",100,false)||null,text(body.billingAddress,"Billing address",2000),text(body.physicalAddress,"Physical address",2000,false)||null,text(body.notes,"Notes",5000,false)||null,body.active!==false];if(id){const rows=await postgresRows("UPDATE clients SET company_name=$1,contact_person=$2,email=$3,phone=$4,registration_number=$5,tax_number=$6,billing_address=$7,physical_address=$8,notes=$9,active=$10,updated_at=now() WHERE id=$11 RETURNING *",[...values,id]);if(!rows[0])throw new Error("Client not found.");return mapClient(rows[0]);}const newId=randomUUID();const rows=await postgresRows("INSERT INTO clients (id,company_name,contact_person,email,phone,registration_number,tax_number,billing_address,physical_address,notes,active) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *",[newId,...values]);return mapClient(rows[0]);}

async function allocateNumber(client:PoolClient,type:"quote"|"invoice",date:string){const year=new Date(`${date}T00:00:00Z`).getUTCFullYear();const result=await client.query(`INSERT INTO document_sequences (document_type,document_year,last_number) VALUES ($1,$2,1) ON CONFLICT(document_type,document_year) DO UPDATE SET last_number=document_sequences.last_number+1 RETURNING last_number`,[type,year]);return `CN-${type==="quote"?"Q":"I"}-${year}-${String(result.rows[0].last_number).padStart(4,"0")}`;}
async function insertLines(client:PoolClient,kind:"quote"|"invoice",documentId:string,lines:ReturnType<typeof parseDocumentInput>["totals"]["lines"]){const table=kind==="quote"?"quote_items":"invoice_items";const foreign=kind==="quote"?"quote_id":"invoice_id";for(const [position,line] of lines.entries())await client.query(`INSERT INTO ${table} (id,${foreign},position,description,quantity_milli,unit,unit_price_cents,discount_cents,line_total_cents) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[randomUUID(),documentId,position,line.description,line.quantityMilli,line.unit,line.unitPriceCents,line.discountCents,line.lineTotalCents]);}

async function settingsTax(){const settings=await getCompanySettings();return settings.vatEnabled?settings.vatBasisPoints:0;}
export async function createQuote(body:Record<string,unknown>,userId:string){const parsed=parseDocumentInput(body,await settingsTax());return withPostgresTransaction(async client=>{if(!(await getClient(parsed.clientId,client)))throw new Error("Client not found.");const id=randomUUID();const number=await allocateNumber(client,"quote",parsed.issueDate);await client.query(`INSERT INTO quotes (id,quote_number,client_id,issue_date,expiry_date,reference,description,status,subtotal_cents,discount_cents,tax_cents,total_cents,notes,terms,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,'DRAFT',$8,$9,$10,$11,$12,$13,$14)`,[id,number,parsed.clientId,parsed.issueDate,parsed.secondaryDate,parsed.reference||null,parsed.description||null,parsed.totals.subtotalCents,parsed.totals.discountCents,parsed.totals.taxCents,parsed.totals.totalCents,parsed.notes||null,parsed.terms||null,userId]);await insertLines(client,"quote",id,parsed.totals.lines);return{id,number};});}
export async function createInvoice(body:Record<string,unknown>,userId:string){const parsed=parseDocumentInput(body,await settingsTax());return withPostgresTransaction(async client=>{if(!(await getClient(parsed.clientId,client)))throw new Error("Client not found.");const id=randomUUID();const number=await allocateNumber(client,"invoice",parsed.issueDate);await client.query(`INSERT INTO invoices (id,invoice_number,client_id,invoice_date,due_date,reference,description,status,subtotal_cents,discount_cents,tax_cents,total_cents,amount_paid_cents,balance_due_cents,notes,payment_terms,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,'DRAFT',$8,$9,$10,$11,0,$11,$12,$13,$14)`,[id,number,parsed.clientId,parsed.issueDate,parsed.secondaryDate,parsed.reference||null,parsed.description||null,parsed.totals.subtotalCents,parsed.totals.discountCents,parsed.totals.taxCents,parsed.totals.totalCents,parsed.notes||null,parsed.terms||null,userId]);await insertLines(client,"invoice",id,parsed.totals.lines);return{id,number};});}

async function linesFor(kind:"quote"|"invoice",id:string){const table=kind==="quote"?"quote_items":"invoice_items";const foreign=kind==="quote"?"quote_id":"invoice_id";return (await postgresRows(`SELECT * FROM ${table} WHERE ${foreign}=$1 ORDER BY position`,[id])).map(mapLine);}
export async function getQuote(id:string):Promise<QuoteRecord|null>{const r=(await postgresRows(`SELECT q.*,c.company_name,(SELECT invoice_number FROM invoices WHERE source_quote_id=q.id) source_invoice_number,(SELECT id FROM invoices WHERE source_quote_id=q.id) source_invoice_id FROM quotes q JOIN clients c ON c.id=q.client_id WHERE q.id=$1`,[id]))[0];if(!r)return null;return{id:String(r.id),quoteNumber:String(r.quote_number),clientId:String(r.client_id),clientName:String(r.company_name),issueDate:dateOnly(r.issue_date),expiryDate:dateOnly(r.expiry_date),reference:r.reference?String(r.reference):null,description:r.description?String(r.description):null,status:String(r.status),subtotalCents:n(r.subtotal_cents),discountCents:n(r.discount_cents),taxCents:n(r.tax_cents),totalCents:n(r.total_cents),notes:r.notes?String(r.notes):null,terms:r.terms?String(r.terms):null,finalizedAt:iso(r.finalized_at),pdfObjectKey:r.pdf_object_key?String(r.pdf_object_key):null,sourceInvoiceId:r.source_invoice_id?String(r.source_invoice_id):null,createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!,lines:await linesFor("quote",id)};}
export async function getInvoice(id:string):Promise<InvoiceRecord|null>{const r=(await postgresRows(`SELECT i.*,c.company_name,q.quote_number source_quote_number FROM invoices i JOIN clients c ON c.id=i.client_id LEFT JOIN quotes q ON q.id=i.source_quote_id WHERE i.id=$1`,[id]))[0];if(!r)return null;const balance=n(r.total_cents)-n(r.amount_paid_cents);let status=String(r.status);if(isInvoiceOverdue({status,dueDate:dateOnly(r.due_date),balanceDueCents:balance}))status="OVERDUE";return{id:String(r.id),invoiceNumber:String(r.invoice_number),clientId:String(r.client_id),clientName:String(r.company_name),sourceQuoteId:r.source_quote_id?String(r.source_quote_id):null,sourceQuoteNumber:r.source_quote_number?String(r.source_quote_number):null,invoiceDate:dateOnly(r.invoice_date),dueDate:dateOnly(r.due_date),reference:r.reference?String(r.reference):null,description:r.description?String(r.description):null,status,subtotalCents:n(r.subtotal_cents),discountCents:n(r.discount_cents),taxCents:n(r.tax_cents),totalCents:n(r.total_cents),amountPaidCents:n(r.amount_paid_cents),balanceDueCents:balance,notes:r.notes?String(r.notes):null,paymentTerms:r.payment_terms?String(r.payment_terms):null,finalizedAt:iso(r.finalized_at),pdfObjectKey:r.pdf_object_key?String(r.pdf_object_key):null,createdAt:iso(r.created_at)!,updatedAt:iso(r.updated_at)!,lines:await linesFor("invoice",id)};}

export async function listQuotes(search="",status=""){const rows=await postgresRows(`SELECT q.id FROM quotes q JOIN clients c ON c.id=q.client_id WHERE ($1='' OR q.quote_number ILIKE '%'||$1||'%' OR c.company_name ILIKE '%'||$1||'%') AND ($2='' OR q.status=$2) AND q.archived_at IS NULL ORDER BY q.created_at DESC`,[search.slice(0,200),status]);return Promise.all(rows.map(r=>getQuote(String(r.id))));}
export async function listInvoices(search="",status=""){const rows=await postgresRows(`SELECT i.id FROM invoices i JOIN clients c ON c.id=i.client_id WHERE ($1='' OR i.invoice_number ILIKE '%'||$1||'%' OR c.company_name ILIKE '%'||$1||'%') AND ($2='' OR i.status=$2 OR ($2='OVERDUE' AND i.status IN ('ISSUED','PARTIALLY_PAID') AND i.due_date<CURRENT_DATE AND i.balance_due_cents>0)) AND i.archived_at IS NULL ORDER BY i.created_at DESC`,[search.slice(0,200),status]);return Promise.all(rows.map(r=>getInvoice(String(r.id))));}

export async function updateDraft(kind:"quote"|"invoice",id:string,body:Record<string,unknown>){const parsed=parseDocumentInput(body,await settingsTax());return withPostgresTransaction(async client=>{const table=kind==="quote"?"quotes":"invoices";const itemTable=kind==="quote"?"quote_items":"invoice_items";const row=(await client.query(`SELECT status FROM ${table} WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!row)throw new Error("Document not found.");if(row.status!=="DRAFT")throw new Error("Only draft documents can be edited.");if(!(await getClient(parsed.clientId,client)))throw new Error("Client not found.");if(kind==="quote")await client.query(`UPDATE quotes SET client_id=$2,issue_date=$3,expiry_date=$4,reference=$5,description=$6,subtotal_cents=$7,discount_cents=$8,tax_cents=$9,total_cents=$10,notes=$11,terms=$12,updated_at=now() WHERE id=$1`,[id,parsed.clientId,parsed.issueDate,parsed.secondaryDate,parsed.reference||null,parsed.description||null,parsed.totals.subtotalCents,parsed.totals.discountCents,parsed.totals.taxCents,parsed.totals.totalCents,parsed.notes||null,parsed.terms||null]);else await client.query(`UPDATE invoices SET client_id=$2,invoice_date=$3,due_date=$4,reference=$5,description=$6,subtotal_cents=$7,discount_cents=$8,tax_cents=$9,total_cents=$10,balance_due_cents=$10,notes=$11,payment_terms=$12,updated_at=now() WHERE id=$1`,[id,parsed.clientId,parsed.issueDate,parsed.secondaryDate,parsed.reference||null,parsed.description||null,parsed.totals.subtotalCents,parsed.totals.discountCents,parsed.totals.taxCents,parsed.totals.totalCents,parsed.notes||null,parsed.terms||null]);await client.query(`DELETE FROM ${itemTable} WHERE ${kind==="quote"?"quote_id":"invoice_id"}=$1`,[id]);await insertLines(client,kind,id,parsed.totals.lines);return{id};});}

async function snapshotFor(client:PoolClient,kind:"quote"|"invoice",id:string):Promise<FinancialSnapshot>{const table=kind==="quote"?"quotes":"invoices";const itemTable=kind==="quote"?"quote_items":"invoice_items";const foreign=kind==="quote"?"quote_id":"invoice_id";const row=(await client.query(`SELECT * FROM ${table} WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!row)throw new Error("Document not found.");if(row.status!=="DRAFT")throw new Error("Only a draft can be finalized.");const clientRecord=await getClient(row.client_id,client);if(!clientRecord)throw new Error("Client not found.");const settings=await getCompanySettings(client);const lines=(await client.query(`SELECT * FROM ${itemTable} WHERE ${foreign}=$1 ORDER BY position`,[id])).rows.map(mapLine);if(!lines.length)throw new Error("Document has no line items.");const includeBank=kind==="invoice"?settings.showBankOnInvoices:settings.showBankOnQuotes;const snapshotSettings=includeBank?settings:{...settings,bankName:null,bankAccountName:null,bankAccountNumber:null,bankBranchCode:null,bankAccountType:null,bankSwiftBic:null,paymentReferenceInstructions:null};return{kind,number:String(kind==="quote"?row.quote_number:row.invoice_number),issueDate:dateOnly(kind==="quote"?row.issue_date:row.invoice_date),secondaryDate:dateOnly(kind==="quote"?row.expiry_date:row.due_date),reference:row.reference,description:row.description,company:snapshotSettings,client:clientRecord,lines,subtotalCents:n(row.subtotal_cents),discountCents:n(row.discount_cents),taxCents:n(row.tax_cents),totalCents:n(row.total_cents),amountPaidCents:kind==="invoice"?n(row.amount_paid_cents):undefined,balanceDueCents:kind==="invoice"?n(row.balance_due_cents):undefined,notes:row.notes,terms:kind==="quote"?row.terms:row.payment_terms};}

export async function finalizeFinancialDocument(kind:"quote"|"invoice",id:string,userId:string){const db=await getPostgresPool().connect();let objectKey="";try{await db.query("BEGIN");const snapshot=await snapshotFor(db,kind,id);const pdf=await generateFinancialPdf(snapshot);const year=new Date(`${snapshot.issueDate}T00:00:00Z`).getUTCFullYear();objectKey=`${kind==="quote"?"quotes":"invoices"}/${year}/${snapshot.number}.pdf`;await uploadR2Object({key:objectKey,body:pdf,contentType:"application/pdf",metadata:{documentNumber:snapshot.number,documentType:kind}});if(!(await r2ObjectExists(objectKey)))throw new Error("PDF archive verification failed.");const table=kind==="quote"?"quotes":"invoices";const status=kind==="quote"?"SENT":"ISSUED";await db.query(`UPDATE ${table} SET status=$2,finalized_snapshot=$3::jsonb,pdf_object_key=$4,finalized_at=now(),finalized_by=$5,updated_at=now() WHERE id=$1 AND status='DRAFT'`,[id,status,JSON.stringify(snapshot),objectKey,userId]);await db.query("COMMIT");return{number:snapshot.number,objectKey};}catch(error){await db.query("ROLLBACK").catch(()=>{});if(objectKey)await deleteR2Object(objectKey).catch(()=>{});throw error;}finally{db.release();}}

export async function getFinalizedPdf(kind:"quote"|"invoice",id:string){const table=kind==="quote"?"quotes":"invoices";const row=(await postgresRows(`SELECT ${kind==="quote"?"quote_number":"invoice_number"} number,pdf_object_key FROM ${table} WHERE id=$1`,[id]))[0];if(!row||!row.pdf_object_key)throw new Error("Finalized PDF not found.");return{number:String(row.number),objectKey:String(row.pdf_object_key)};}

export async function setQuoteStatus(id:string,status:string){const allowed=new Set(["SENT","ACCEPTED","DECLINED","EXPIRED"]);if(!allowed.has(status))throw new Error("Invalid quote status.");return withPostgresTransaction(async client=>{const row=(await client.query("SELECT status FROM quotes WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!row)throw new Error("Quote not found.");const transitions:Record<string,string[]>={SENT:["ACCEPTED","DECLINED","EXPIRED"],ACCEPTED:[],DECLINED:[],EXPIRED:[]};if(!transitions[row.status]?.includes(status)&&row.status!==status)throw new Error(`Cannot change ${row.status} to ${status}.`);await client.query("UPDATE quotes SET status=$2,updated_at=now() WHERE id=$1",[id,status]);return{status};});}

export async function convertQuoteToInvoice(quoteId:string,userId:string,invoiceDate:string,dueDate:string){const issue=isoDate(invoiceDate,"Invoice date"),due=isoDate(dueDate,"Due date");return withPostgresTransaction(async client=>{const quote=(await client.query("SELECT * FROM quotes WHERE id=$1 FOR UPDATE",[quoteId])).rows[0];if(!quote)throw new Error("Quote not found.");if(quote.status!=="ACCEPTED")throw new Error("Only an accepted quote can be converted.");const duplicate=(await client.query("SELECT id FROM invoices WHERE source_quote_id=$1",[quoteId])).rows[0];if(duplicate)throw new Error("This quote has already been converted.");const id=randomUUID(),number=await allocateNumber(client,"invoice",issue);const settings=await getCompanySettings(client);await client.query(`INSERT INTO invoices (id,invoice_number,source_quote_id,client_id,invoice_date,due_date,reference,description,status,subtotal_cents,discount_cents,tax_cents,total_cents,amount_paid_cents,balance_due_cents,notes,payment_terms,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'DRAFT',$9,$10,$11,$12,0,$12,$13,$14,$15)`,[id,number,quoteId,quote.client_id,issue,due,quote.reference,quote.description,quote.subtotal_cents,quote.discount_cents,quote.tax_cents,quote.total_cents,quote.notes,settings.invoiceTerms,userId]);const lines=(await client.query("SELECT * FROM quote_items WHERE quote_id=$1 ORDER BY position",[quoteId])).rows.map(mapLine).map(line=>({...line,quantityMilli:line.quantityMilli,unitPriceCents:line.unitPriceCents,discountCents:line.discountCents}));await insertLines(client,"invoice",id,lines);await client.query("UPDATE quotes SET status='CONVERTED',updated_at=now() WHERE id=$1",[quoteId]);return{id,number};});}

export async function listPayments(invoiceId:string):Promise<PaymentRecord[]>{const rows=await postgresRows("SELECT * FROM payments WHERE invoice_id=$1 AND voided_at IS NULL ORDER BY payment_date DESC,created_at DESC",[invoiceId]);return rows.map(r=>({id:String(r.id),paymentDate:dateOnly(r.payment_date),amountCents:n(r.amount_cents),paymentMethod:String(r.payment_method),reference:r.reference?String(r.reference):null,notes:r.notes?String(r.notes):null,recordedBy:String(r.recorded_by),createdAt:iso(r.created_at)!}));}
export async function recordPayment(invoiceId:string,body:Record<string,unknown>,userId:string){const amount=parseMoneyToCents(body.amount),paymentDate=isoDate(body.paymentDate,"Payment date"),method=text(body.paymentMethod,"Payment method",100),reference=text(body.reference,"Reference",200,false)||null,notes=text(body.notes,"Notes",2000,false)||null;if(amount<=0)throw new Error("Payment must be greater than zero.");return withPostgresTransaction(async client=>{const invoice=(await client.query("SELECT total_cents,status FROM invoices WHERE id=$1 FOR UPDATE",[invoiceId])).rows[0];if(!invoice)throw new Error("Invoice not found.");if(!["ISSUED","PARTIALLY_PAID","OVERDUE"].includes(invoice.status))throw new Error("Payments can only be recorded against an issued invoice.");const paid=n((await client.query("SELECT COALESCE(SUM(amount_cents),0) paid FROM payments WHERE invoice_id=$1 AND voided_at IS NULL",[invoiceId])).rows[0].paid);const total=n(invoice.total_cents);if(amount>total-paid)throw new Error("Payment exceeds the outstanding balance.");const newPaid=paid+amount,balance=total-newPaid,status=balance===0?"PAID":"PARTIALLY_PAID";const id=randomUUID();await client.query("INSERT INTO payments (id,invoice_id,payment_date,amount_cents,payment_method,reference,notes,recorded_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)",[id,invoiceId,paymentDate,amount,method,reference,notes,userId]);await client.query("UPDATE invoices SET amount_paid_cents=$2,balance_due_cents=$3,status=$4,updated_at=now() WHERE id=$1",[invoiceId,newPaid,balance,status]);return{id,balanceDueCents:balance,status};});}

export async function cancelInvoice(id:string){return withPostgresTransaction(async client=>{const row=(await client.query("SELECT status FROM invoices WHERE id=$1 FOR UPDATE",[id])).rows[0];if(!row)throw new Error("Invoice not found.");if(row.status==="PAID")throw new Error("A paid invoice cannot be cancelled.");if(row.status==="CANCELLED")return{status:"CANCELLED"};await client.query("UPDATE invoices SET status='CANCELLED',updated_at=now() WHERE id=$1",[id]);return{status:"CANCELLED"};});}

export async function dashboardFinancialSummary(){const [q,i,p]=await Promise.all([postgresRows(`SELECT COUNT(*) FILTER(WHERE status='DRAFT')::int draft,COUNT(*) FILTER(WHERE status='SENT')::int outstanding,COUNT(*) FILTER(WHERE status='ACCEPTED')::int accepted FROM quotes WHERE archived_at IS NULL`),postgresRows(`SELECT COUNT(*) FILTER(WHERE status IN ('ISSUED','PARTIALLY_PAID') AND balance_due_cents>0)::int unpaid,COUNT(*) FILTER(WHERE status IN ('ISSUED','PARTIALLY_PAID') AND due_date<CURRENT_DATE AND balance_due_cents>0)::int overdue,COALESCE(SUM(balance_due_cents) FILTER(WHERE status IN ('ISSUED','PARTIALLY_PAID')),0)::bigint outstanding_value FROM invoices WHERE archived_at IS NULL`),postgresRows(`SELECT COALESCE(SUM(amount_cents),0)::bigint paid_month FROM payments WHERE voided_at IS NULL AND date_trunc('month',payment_date)=date_trunc('month',CURRENT_DATE)`)]);return{draftQuotes:n(q[0].draft),outstandingQuotes:n(q[0].outstanding),acceptedQuotes:n(q[0].accepted),unpaidInvoices:n(i[0].unpaid),overdueInvoices:n(i[0].overdue),outstandingInvoiceCents:n(i[0].outstanding_value),paidThisMonthCents:n(p[0].paid_month)};}
