BEGIN;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS archived_by text REFERENCES "user"(id) ON DELETE SET NULL;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS archived_by text REFERENCES "user"(id) ON DELETE SET NULL;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS archived_by text REFERENCES "user"(id) ON DELETE SET NULL;
COMMIT;
