import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { getAccountAccess } from "@/lib/admin-access";
import { deleteFolder,getFolderBreadcrumbs,getFolderById,moveFolder,renameFolder } from "@/lib/documents";

function validName(value:unknown){const name=typeof value==="string"?value.trim():"";if(!name||name.length>100||/[\\/:*?"<>|]/.test(name))throw new Error("Use a valid folder name.");return name;}
async function authenticate(){return auth.api.getSession({headers:await headers()});}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!(await authenticate()))return Response.json({error:"Unauthorized"},{status:401});try{const id=(await params).id;if(!(await getFolderById(id)))return Response.json({error:"Folder not found."},{status:404});const body=await request.json()as Record<string,unknown>;if(body.action==="rename")await renameFolder(id,validName(body.name));else if(body.action==="move"){const parentId=typeof body.parentId==="string"&&body.parentId?body.parentId:null;if(parentId===id)throw new Error("A folder cannot contain itself.");if(parentId){const ancestors=await getFolderBreadcrumbs(parentId);if(ancestors.some(folder=>folder.id===id))throw new Error("A folder cannot be moved into one of its descendants.");}await moveFolder(id,parentId);}else throw new Error("Unsupported folder action.");return Response.json({success:true});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to update folder."},{status:400});}}
export async function DELETE(_request:Request,{params}:{params:Promise<{id:string}>}){const access=await getAccountAccess(await headers());if(!access?.isAdmin)return Response.json({error:"Administrator access is required."},{status:403});try{await deleteFolder((await params).id);return Response.json({success:true});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to delete folder."},{status:400});}}
