import nodemailer from "nodemailer";

type NotificationEnquiry = {
  reference: string;
  intent: string;
  service: string;
  projectType: string | null;
  fullName: string;
  company: string;
  role: string | null;
  email: string;
  phone: string;
  location: string | null;
  preferredContact: string;
  details: Record<string, unknown>;
};

const labels: Record<string, string> = {
  quote: "Quote request", callback: "Callback request", general: "General enquiry",
  "healthcare-technology": "Healthcare Technology", "medical-equipment": "Medical Equipment & Consumables",
  "professional-services": "Professional Services", "strategic-partnerships": "Strategic Partnerships",
};

function escapeHtml(value: string) {
  return value.replace(/[&<>"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character] ?? character);
}

export async function sendEnquiryNotification(enquiry: NotificationEnquiry) {
  const host = process.env.SMTP_HOST;
  const port = Number(process.env.SMTP_PORT || "587");
  const user = process.env.SMTP_USER;
  const password = process.env.SMTP_PASSWORD;
  const to = process.env.ENQUIRY_NOTIFICATION_EMAIL || user;

  if (!host || !user || !password || !to || !Number.isInteger(port)) {
    console.warn("Enquiry email notification skipped: SMTP configuration is incomplete.");
    return false;
  }

  const rows = [
    ["Reference", enquiry.reference], ["Request", labels[enquiry.intent] ?? enquiry.intent],
    ["Service", labels[enquiry.service] ?? enquiry.service], ["Project type", enquiry.projectType],
    ["Name", enquiry.fullName], ["Company", enquiry.company], ["Role", enquiry.role],
    ["Email", enquiry.email], ["Phone", enquiry.phone], ["Location", enquiry.location],
    ["Preferred contact", enquiry.preferredContact],
    ...Object.entries(enquiry.details).map(([key, value]) => [key.replace(/([A-Z])/g, " $1"), String(value)]),
  ].filter((row): row is [string, string] => Boolean(row[1]));

  const text = rows.map(([label, value]) => `${label}: ${value}`).join("\n\n");
  const htmlRows = rows.map(([label, value]) => `<tr><td style="padding:10px 14px;border-bottom:1px solid #e2e8f0;color:#64748b;font-weight:700;vertical-align:top">${escapeHtml(label)}</td><td style="padding:10px 14px;border-bottom:1px solid #e2e8f0;color:#0f172a;white-space:pre-wrap">${escapeHtml(value)}</td></tr>`).join("");
  const subject = `[${enquiry.reference}] ${labels[enquiry.intent] ?? "Enquiry"}: ${labels[enquiry.service] ?? enquiry.service}`;

  const transporter = nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    requireTLS: port === 587,
    auth: { user, pass: password },
  });

  await transporter.sendMail({
    from: `"CustoNexus Website" <${user}>`,
    to,
    replyTo: enquiry.email,
    subject,
    text,
    html: `<div style="font-family:Arial,sans-serif;max-width:760px;margin:auto"><div style="background:#071a3d;color:white;padding:26px;border-radius:18px 18px 0 0"><div style="font-size:12px;letter-spacing:2px;color:#bfdbfe;font-weight:700">CUSTONEXUS WEBSITE</div><h1 style="margin:10px 0 0;font-size:25px">New ${escapeHtml(labels[enquiry.intent] ?? "enquiry")}</h1></div><table style="width:100%;border-collapse:collapse;border:1px solid #e2e8f0">${htmlRows}</table><p style="color:#64748b;font-size:13px;margin-top:18px">This notification was generated by custonexus.com. The full record is also available in the Secure Archive.</p></div>`,
    headers: { "X-CustoNexus-Enquiry": enquiry.reference },
  });

  console.info("Enquiry email notification sent", { reference: enquiry.reference });
  return true;
}
