import { randomUUID } from "node:crypto";
import { headers } from "next/headers";
import { auth } from "@/lib/auth";
import { getDocumentById,getFolderById,insertDocument,moveDocument,renameDocument } from "@/lib/documents";
import { buildDocumentObjectKey } from "@/lib/storage/r2";
import { copyStoredDocument } from "@/lib/storage/documents";

function validName(value:unknown){const name=typeof value==="string"?value.trim():"";if(!name||name.length>180||/[\\/:*?"<>|]/.test(name))throw new Error("Use a valid file name.");return name;}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const session=await auth.api.getSession({headers:await headers()});if(!session)return Response.json({error:"Unauthorized"},{status:401});try{const source=await getDocumentById((await params).id);if(!source)return Response.json({error:"File not found."},{status:404});const body=await request.json()as Record<string,unknown>,action=String(body.action),folderId=typeof body.folderId==="string"&&body.folderId?body.folderId:null;if(folderId&&!(await getFolderById(folderId)))throw new Error("Destination folder not found.");if(action==="move")await moveDocument(source.id,folderId);else if(action==="rename")await renameDocument(source.id,validName(body.name));else if(action==="copy"){if(!source.objectKey)throw new Error("Copy is only available for R2 files.");const id=randomUUID(),createdAt=new Date(),name=validName(body.name||`Copy of ${source.originalName}`),objectKey=buildDocumentObjectKey(id,name,createdAt);await copyStoredDocument(source.objectKey,objectKey);await insertDocument({...source,id,name,originalName:name,objectKey,filePath:null,folderId,uploadedBy:session.user.id,createdAt:createdAt.toISOString(),updatedAt:createdAt.toISOString(),archivedAt:null});}else throw new Error("Unsupported file action.");return Response.json({success:true});}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to organise file."},{status:400});}}
